### ISSUE TITLE
Update API registration string

### ISSUE THREAD

**Issue by pierceboggan** [microsoft/vscode-azureapicenter#142]
![image](https://github.com/microsoft/vscode-azureapicenter/assets/1091304/7942f4e7-7d80-4142-b863-7179fea6142a)
Change string "Step by step" to "Manual"

**Comment by formulahendry** [comment]
@pierceboggan  This update has been merged into dev branch.
![image](https://github.com/microsoft/vscode-azureapicenter/assets/1050213/0ae3e75c-c372-4856-a09a-bfcfef264dbf)
