### ISSUE TITLE
Azure Account extension that Azure Api Center extension depends on for authentication will be deprecated in January 2025.

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-azureapicenter#168]
Hello 👋,

**Azure Account extension that Azure Api Center extension depends on for authentication will be deprecated in January 2025.** Please see https://github.com/microsoft/vscode-azure-account/issues/964 for more details.

After taking a look at the Azure Api Center extension, we recommend onboarding it onto our [Azure Resources API](https://github.com/microsoft/vscode-azureresourcegroups/tree/main/api). A great example of an extension migrating onto the Azure Resources API is the Azure Spring Apps extension: https://github.com/microsoft/vscode-azurespringcloud/pull/49.

Please reach out to me on Teams for questions or support.

**Comment by wenytang-ms** [comment]
https://github.com/microsoft/vscode-azureapicenter/pull/192

**Comment by wenytang-ms** [comment]
@alexweininger thank you for your reminder, we already remove the 'azure-account' extension and do sign in flow leverage vscode authentication session.
so just close this issue.

**Comment by alexweininger** [comment]
Awesome, thank you @wenytang-ms
