### ISSUE TITLE
“No matching resource found" if choosing Envrionments or Deployments for Detect breaking change

### ISSUE THREAD

**Issue by hellyzh** [microsoft/vscode-azureapicenter#169]
Detect breaking change -> Azure API Center -> choose service -> Environments or Deployments of APIs,
The environment or deployment can't be listed with following error
![image](https://github.com/microsoft/vscode-azureapicenter/assets/49181894/df42952c-4464-4323-9774-a83084c2bd3e)

**Comment by formulahendry** [comment]
This is a known issue and already in our backlog: https://github.com/microsoft/vscode-azureapicenter/issues/87
