### ISSUE TITLE
If no subscription is selected, the tree view should also not select any subscription.

### ISSUE THREAD

**Issue by Annefch** [microsoft/vscode-azureapicenter#197]
API center version:v1.1.2024070409

Do not selected any subscription and click the "OK" button

<img width="632" alt="image" src="https://github.com/microsoft/vscode-azureapicenter/assets/33708747/b0040978-0763-4a0d-86ec-2b34d85bd14a">

The Tree View will show all Azure Subs

![image](https://github.com/microsoft/vscode-azureapicenter/assets/33708747/5af1b17a-15d0-4138-b89e-40031befdf21)

should like this:
![image](https://github.com/microsoft/vscode-azureapicenter/assets/33708747/f0d4cffb-9c8e-4baa-bec6-e8eef826b0e7)

**Comment by wenytang-ms** [comment]
https://github.com/microsoft/vscode-azureapicenter/pull/199

**Comment by wenytang-ms** [comment]
@Annefch please help verify against this bits https://github.com/microsoft/vscode-azureapicenter/actions/runs/9877545770

**Comment by hellyzh** [comment]
@wenytang-ms @Annefch Verified and close the issue
