### ISSUE TITLE
Re-ask of log into my tenant again

### ISSUE THREAD

**Issue by juliajuju93** [microsoft/vscode-azureapicenter#237]
I still have the bug that every time I am opening up the API Center extension it wants me to log into my tenant again. And then I always get this error message:
![image](https://github.com/user-attachments/assets/19d0afee-4b99-4973-a121-de217f986bb5)

**Comment by wenytang-ms** [comment]
https://github.com/microsoft/vscode-azureapicenter/pull/265

**Comment by wenytang-ms** [comment]
Hi @juliajuju93 now you may access the latest API Center preview to try, and this preview resolved this error
