### ISSUE TITLE
Should show 'Select xxx item' instead of 'Select {0}'

### ISSUE THREAD

**Issue by formulahendry** [microsoft/vscode-azureapicenter#269]
Repro steps:

1. Trigger command from Command Palette.  e.g. Export API Specification Document

Actual:
![image](https://github.com/user-attachments/assets/2f7af463-2c99-432d-aa81-293bd3a9a5d2)
![image](https://github.com/user-attachments/assets/fecdb5cc-29fe-4e1b-b78d-d454f4851df2)

Expect: to show as:
- Select Subscription
- Select API Center Service

Should be an regression from https://github.com/microsoft/vscode-azureapicenter/pull/192/files#diff-3b26e2c6749863538fbe756b9eb0e37aaa43b559e370bd6daf7aaa84a871a158L13
`public readonly childTypeLabel: string = UiStrings.SubscriptionTreeItemChildTypeLabel;` is removed.

**Comment by wenytang-ms** [comment]
https://github.com/microsoft/vscode-azureapicenter/pull/270
